### ISSUE TITLE
「セミナーについて作成」

### ISSUE THREAD

**Issue by omorirenka** [kikuchihibiki/smile#5]

**Comment by kikuchihibiki** [comment]
## 新人研修タブの作成
- [x] htmlの雛形作成
- [x] cssでのタブ切り替えの実装
## スマイルトレーニングタブの作成
- [x] htmlの雛形作成
- [x] cssでのタブ切り替えの実装
## ホスピタリティタグの作成
- [x] htmlの雛形作成
- [x] cssでのタブ切り替えの実装
- [x] cssでコンテンツの位置の指定

**Comment by kikuchihibiki** [comment]
デザイン以外は完了
